const demo = {
  user: { name: "Alex Smith", initials: "AS" },
  spaces: [{ id: "farsi", name: "Farsi Foundations", description: "A shared home for words that stick.", code: "DUST-4827", fields: ["Farsi", "Pronunciation", "English", "Mnemonic"], members: [{ name: "Alex Smith", initials: "AS", role: "Owner" }, { name: "Maya Chen", initials: "MC", role: "Member" }, { name: "Omar Salah", initials: "OS", role: "Member" }], cards: [
    { id: "dust", values: ["دوست", "dust", "friend", "Think: a friend you trust so much you can share the dustiest old stories."], author: "Maya" },
    { id: "book", values: ["کتاب", "ketâb", "book", "Picture a cat climbing into a big book: ketâb has a cat tucked inside."], author: "Omar" },
    { id: "hello", values: ["سلام", "salâm", "hello", "A warm salaam is a hello that opens the room."], author: "Alex" }
  ] }]
};

const persisted = JSON.parse(localStorage.getItem("mnemo-demo-data") || "null");
const state = { data: persisted || demo, screen: "auth", authMode: "signup", spaceId: "farsi", cardId: "dust", studyIndex: 0, phase: 0, search: "" };
const app = document.querySelector("#app");
const modalRoot = document.querySelector("#modal-root");
const toastRoot = document.querySelector("#toast-root");

function save() { localStorage.setItem("mnemo-demo-data", JSON.stringify(state.data)); }
function space() { return state.data.spaces.find((item) => item.id === state.spaceId) || state.data.spaces[0]; }
function esc(value) { return String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[char])); }
function toast(message) { toastRoot.innerHTML = `<div class="toast">${esc(message)}</div>`; setTimeout(() => toastRoot.innerHTML = "", 2800); }
function initials(name) { return name.split(" ").map((word) => word[0]).join("").slice(0,2).toUpperCase(); }
function button(label, action, variant = "") { return `<button class="btn ${variant}" data-action="${action}">${label}</button>`; }

function render() { if (state.screen === "auth") renderAuth(); else renderApp(); }
function renderAuth() {
  const login = state.authMode === "login";
  app.innerHTML = `<section class="auth"><div class="auth-art"><div class="brand"><span class="brand-mark"></span>mnemo</div><div class="auth-copy"><div class="eyebrow">Learn by connection</div><h1>Give every memory a place to land.</h1><p>Build vivid, shared mnemonic journeys with the people learning alongside you.</p></div><footer>Small connections become lasting memory.</footer></div><div class="auth-panel"><form class="auth-form" id="auth-form"><h2>${login ? "Welcome back." : "Make learning stick."}</h2><p>${login ? "Sign in to continue your learning journey." : "Create a space for the things you want to remember."}</p>${!login ? `<div class="form-row"><label for="name">Your name</label><input id="name" required placeholder="Alex Smith" /></div>` : ""}<div class="form-row"><label for="email">Email</label><input id="email" type="email" required placeholder="you@example.com" /></div><div class="form-row"><label for="password">Password</label><input id="password" type="password" required placeholder="••••••••" /></div>${button(login ? "Sign in" : "Create account", "submit-auth", "primary block")}<p class="auth-switch">${login ? "New to Mnemo?" : "Already have an account?"} <button type="button" class="text-button" data-action="toggle-auth">${login ? "Create an account" : "Sign in"}</button></p></form></div></section>`;
}
function shell(content) {
  const active = state.screen;
  const current = space();
  return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark"></span>mnemo</div><button class="space-switcher" data-action="go-dashboard"><span class="caption">Current space</span><strong>${esc(current.name)}⌄</strong></button><nav class="nav"><button class="${active === "dashboard" ? "active" : ""}" data-action="go-dashboard"><span class="nav-icon">▦</span><span class="nav-label">Overview</span></button><button class="${active === "cards" ? "active" : ""}" data-action="go-cards"><span class="nav-icon">▤</span><span class="nav-label">Cards</span></button><button class="${active === "study" ? "active" : ""}" data-action="go-study"><span class="nav-icon">✦</span><span class="nav-label">Study</span></button><button class="${active === "settings" ? "active" : ""}" data-action="go-settings"><span class="nav-icon">⚙</span><span class="nav-label">Settings</span></button></nav><div class="sidebar-user"><span class="avatar">${state.data.user.initials}</span><div>${esc(state.data.user.name)}<small>Personal account</small></div></div></aside><main class="main">${content}</main></div>`;
}
function renderApp() { const views = { dashboard: dashboardView, cards: cardsView, study: studyView, settings: settingsView }; app.innerHTML = shell((views[state.screen] || dashboardView)()); }
function dashboardView() { const spaces = state.data.spaces; const current = space(); return `<div class="topbar"><div><div class="eyebrow">Your learning spaces</div><h1>Keep the thread going.</h1><p>Small connections become lasting memory.</p></div><div class="actions">${button("＋ Join space", "join-space")}${button("＋ Create space", "create-space", "primary")}</div></div><section class="hero"><div><div class="eyebrow">Your next session</div><h2>${esc(current.name)}</h2><p>Continue with ${current.cards.length} cards waiting for a first look.</p>${button("Start studying ↗", "go-study", "orange")}</div><div class="progress-box"><div class="progress-label"><span>Weekly rhythm</span><span>4 / 6 sessions</span></div><div class="progress"><span style="width:68%"></span></div></div></section><div class="section-head"><h2>Your spaces</h2><span class="card-detail">${spaces.length} active</span></div><section class="space-grid">${spaces.map((item) => `<article class="space-tile"><div class="tile-top"><span class="tag">${item.members.length} learners</span><button class="icon-dot" data-action="open-space" data-id="${item.id}" aria-label="Open ${esc(item.name)}">•••</button></div><div><h3>${esc(item.name)}</h3><p class="card-detail">${esc(item.description)}</p></div><div class="tile-meta"><span>${item.cards.length} cards</span><span>Open space →</span></div></article>`).join("")}</section>`; }
function cardsView() { const current = space(); const query = state.search.toLowerCase(); const cards = current.cards.filter((card) => card.values.some((value) => value.toLowerCase().includes(query))); return `<div class="space-head"><button class="breadcrumbs" data-action="go-dashboard">← All spaces</button><div class="topbar"><div><h1>${esc(current.name)}</h1><p>${esc(current.description)}</p></div><div class="actions">${button("Invite", "invite")}${button("＋ Add card", "add-card", "primary")}</div></div></div><div class="toolbar"><div class="search"><input id="card-search" value="${esc(state.search)}" placeholder="Search every field" /></div><span class="card-detail">${cards.length} of ${current.cards.length} cards</span></div><section class="card-grid">${cards.length ? cards.map((card) => cardTile(card)).join("") : `<div class="empty"><h2>No matching cards</h2><p>Try another word or add a fresh card.</p></div>`}</section>`; }
function cardTile(card) { const current = space(); return `<article class="mnemo-card"><div class="tile-top"><span class="tag">${esc(current.fields[0])}</span><button class="icon-dot" data-action="edit-card" data-id="${card.id}" aria-label="Edit card">•••</button></div><div><h3 class="card-term">${esc(card.values[0])}</h3><p class="card-detail">${esc(card.values[1] || "No pronunciation")} · ${esc(card.values[2] || "No meaning")}</p></div><div class="card-meta"><span>${esc(card.author)} edited</span><span>${current.fields.length} fields</span></div></article>`; }
function studyView() { const current = space(); if (!current.cards.length) return `<div class="study-head"><button class="breadcrumbs" data-action="go-cards">← Back to cards</button></div><div class="empty"><h2>Your study deck is waiting</h2><p>Add a card first, then return here to practise its memory chain.</p>${button("Add your first card", "add-card", "primary")}</div>`; const card = current.cards[state.studyIndex % current.cards.length]; const field = current.fields[Math.min(state.phase, current.fields.length - 1)]; const phaseDots = current.fields.map((_, index) => `<span class="${index <= state.phase ? "active" : ""}"></span>`).join(""); return `<div class="study-head"><button class="breadcrumbs" data-action="go-cards">← Back to cards</button><div class="eyebrow">${esc(current.name)} · Card ${state.studyIndex + 1} / ${current.cards.length}</div></div><section class="study-stage"><div class="study-wrap"><article class="study-card ${state.phase ? "flipped" : ""}"><div class="study-face study-front"><div><div class="eyebrow">${esc(current.fields[0])} · field 1 of ${current.fields.length}</div><div class="phase-dots">${phaseDots}</div></div><div><div class="study-word">${esc(card.values[0])}</div>${card.values[1] ? `<div class="pronunciation">${esc(card.values[1])}</div>` : ""}</div><div class="study-note">Recall the connection before revealing the next cue.</div></div><div class="study-face study-back"><div><div class="eyebrow">${esc(field)} · field ${state.phase + 1} of ${current.fields.length}</div><div class="phase-dots">${phaseDots}</div></div><div class="reveal-block"><div class="eyebrow">${esc(field)}</div><strong>${esc(card.values[state.phase])}</strong></div><div class="study-note">${state.phase < current.fields.length - 1 ? "Take a breath—what comes next?" : "You’ve reached the full memory chain."}</div></div></article></div></section><div class="study-controls">${button("← Previous", "study-prev")}${state.phase < current.fields.length - 1 ? button("Reveal next", "study-reveal", "primary") : button("Got it ✓", "study-next", "primary")}${button("Next card →", "study-next")}</div>`; }
function settingsView() { const current = space(); return `<div class="space-head"><button class="breadcrumbs" data-action="go-cards">← ${esc(current.name)}</button><h1>Space settings</h1><p>Shape the way this group remembers together.</p></div><div class="settings-grid"><section class="panel"><h2>Card fields</h2><p>Fields reveal in this order during study mode. Everyone uses the same structure.</p><div id="field-list">${current.fields.map((field, index) => `<div class="field-row"><span class="field-index">${index + 1}</span><input data-field-index="${index}" value="${esc(field)}" aria-label="Field ${index + 1}" /><button class="btn danger" data-action="delete-field" data-index="${index}" ${current.fields.length <= 2 ? "disabled" : ""}>Remove</button></div>`).join("")}</div>${button("＋ Add field", "add-field")}${button("Save field names", "save-fields", "primary")}</section><aside class="panel"><h2>Members</h2><p>${current.members.length} people are learning here.</p>${current.members.map((member) => `<div class="member-row"><div class="member"><span class="avatar">${member.initials}</span><div>${esc(member.name)}<small>${esc(member.role)}</small></div></div></div>`).join("")}${button("Invite members", "invite", "primary block")}</aside></div>`; }

function openModal(content) { modalRoot.innerHTML = `<div class="modal-backdrop" data-action="close-modal"><section class="modal" role="dialog" aria-modal="true">${content}</section></div>`; }
function closeModal() { modalRoot.innerHTML = ""; }
function spaceModal() { openModal(`<h2>Create a space</h2><p>Start a new learning journey. You can invite friends as soon as it exists.</p><form id="space-form"><div class="form-row"><label for="space-name">Space name</label><input id="space-name" required placeholder="e.g. Farsi Foundations" /></div><div class="form-row"><label for="space-description">Description <span class="card-detail">optional</span></label><textarea id="space-description" placeholder="What are you learning together?"></textarea></div><div class="form-row"><label for="space-fields">Fields <span class="card-detail">separate with commas</span></label><input id="space-fields" required value="Term, Pronunciation, Meaning, Mnemonic" /></div><div class="modal-actions">${button("Cancel", "close-modal")}${button("Create space", "submit-space", "primary")}</div></form>`); }
function cardModal(card = null) { const current = space(); const values = card?.values || current.fields.map(() => ""); openModal(`<h2>${card ? "Edit card" : "Add a card"}</h2><p>Build a memory chain your whole space can use.</p><form id="card-form" data-card-id="${card?.id || ""}">${current.fields.map((field, index) => `<div class="form-row"><label for="card-${index}">${esc(field)}${index === 0 ? "" : " <span class=\"card-detail\">optional</span>"}</label>${index === current.fields.length - 1 ? `<textarea id="card-${index}" ${index === 0 ? "required" : ""}>${esc(values[index])}</textarea>` : `<input id="card-${index}" ${index === 0 ? "required" : ""} value="${esc(values[index])}" />`}</div>`).join("")}<div class="modal-actions">${card ? button("Delete", "delete-card", "danger") : ""}${button("Cancel", "close-modal")}${button("Save card", "submit-card", "primary")}</div></form>`); }
function inviteModal() { const current = space(); openModal(`<h2>Invite a learning partner</h2><p>Share this code with someone you trust. They’ll get full editing access to this space.</p><div class="code">${esc(current.code)}</div><div class="modal-actions">${button("Close", "close-modal")}${button("Copy code", "copy-code", "primary")}</div>`); }
function joinModal() { openModal(`<h2>Join a space</h2><p>Ask a friend for their invite code, then you can learn and edit together.</p><form id="join-form"><div class="form-row"><label for="invite-code">Invite code</label><input id="invite-code" required placeholder="e.g. DUST-4827" /></div><div class="modal-actions">${button("Cancel", "close-modal")}${button("Join space", "submit-join", "primary")}</div></form>`); }

app.addEventListener("submit", (event) => { event.preventDefault(); if (event.target.id === "auth-form") { state.screen = "dashboard"; render(); toast("Welcome to Mnemo — demo mode is active."); } });
document.addEventListener("submit", (event) => event.preventDefault());
app.addEventListener("input", (event) => { if (event.target.id === "card-search") { state.search = event.target.value; renderApp(); document.querySelector("#card-search")?.focus(); } });
document.addEventListener("click", (event) => {
  const trigger = event.target.closest("[data-action]"); if (!trigger) return;
  const action = trigger.dataset.action; const current = space();
  if (action === "close-modal") { if (event.target === trigger || trigger.tagName === "BUTTON") closeModal(); return; }
  if (action === "toggle-auth") { state.authMode = state.authMode === "login" ? "signup" : "login"; renderAuth(); return; }
  if (action === "go-dashboard") { state.screen = "dashboard"; render(); return; }
  if (action === "go-cards") { state.screen = "cards"; state.search = ""; render(); return; }
  if (action === "go-study") { state.screen = "study"; state.phase = 0; render(); return; }
  if (action === "go-settings") { state.screen = "settings"; render(); return; }
  if (action === "create-space") return spaceModal();
  if (action === "join-space") return joinModal();
  if (action === "invite") return inviteModal();
  if (action === "add-card") return cardModal();
  if (action === "edit-card") return cardModal(current.cards.find((item) => item.id === trigger.dataset.id));
  if (action === "open-space") { state.spaceId = trigger.dataset.id; state.screen = "cards"; render(); return; }
  if (action === "copy-code") { navigator.clipboard?.writeText(current.code); trigger.textContent = "Copied ✓"; toast("Invite code copied."); return; }
  if (action === "study-reveal") { state.phase = Math.min(state.phase + 1, current.fields.length - 1); render(); return; }
  if (action === "study-prev") { if (state.phase) state.phase--; else state.studyIndex = (state.studyIndex - 1 + current.cards.length) % current.cards.length; render(); return; }
  if (action === "study-next") { state.studyIndex = (state.studyIndex + 1) % current.cards.length; state.phase = 0; render(); return; }
  if (action === "add-field") { current.fields.push("New field"); save(); render(); return; }
  if (action === "delete-field") { const index = Number(trigger.dataset.index); if (current.fields.length <= 2) return; current.fields.splice(index, 1); current.cards.forEach((card) => card.values.splice(index, 1)); save(); render(); toast("Field removed from every card."); return; }
  if (action === "save-fields") { document.querySelectorAll("[data-field-index]").forEach((input) => { current.fields[Number(input.dataset.fieldIndex)] = input.value.trim() || "Untitled field"; }); save(); toast("Field names saved."); return; }
  if (action === "submit-space") { const form = document.querySelector("#space-form"); if (!form.reportValidity()) return; const name = form.querySelector("#space-name").value.trim(); const fields = form.querySelector("#space-fields").value.split(",").map((value) => value.trim()).filter(Boolean).slice(0,8); if (fields.length < 2) return toast("A space needs at least two fields."); const item = { id: `space-${Date.now()}`, name, description: form.querySelector("#space-description").value.trim() || "A new place for memorable connections.", code: `${name.slice(0,4).toUpperCase()}-${Math.floor(1000 + Math.random()*9000)}`, fields, members:[{ name:state.data.user.name, initials:state.data.user.initials, role:"Owner" }], cards:[] }; state.data.spaces.push(item); state.spaceId=item.id; state.screen="cards"; save(); closeModal(); render(); toast("Space created."); return; }
  if (action === "submit-card") { const form = document.querySelector("#card-form"); if (!form.reportValidity()) return; const values = current.fields.map((_, index) => form.querySelector(`#card-${index}`).value.trim()); const existing = current.cards.find((card) => card.id === form.dataset.cardId); if (existing) { existing.values=values; existing.author=state.data.user.name.split(" ")[0]; } else current.cards.unshift({ id:`card-${Date.now()}`, values, author:state.data.user.name.split(" ")[0] }); save(); closeModal(); render(); toast(existing ? "Card updated." : "Card added to the space."); return; }
  if (action === "delete-card") { const id = document.querySelector("#card-form").dataset.cardId; current.cards = current.cards.filter((card) => card.id !== id); save(); closeModal(); render(); toast("Card deleted."); return; }
  if (action === "submit-join") { const code = document.querySelector("#invite-code").value.trim().toUpperCase(); const matched = state.data.spaces.find((item) => item.code === code); if (!matched) return toast("That invite code is not in this demo yet."); if (!matched.members.some((member) => member.name === state.data.user.name)) matched.members.push({ name:state.data.user.name, initials:state.data.user.initials, role:"Member" }); state.spaceId=matched.id; state.screen="cards"; save(); closeModal(); render(); toast(`You joined ${matched.name}.`); }
});
render();
