const config = window.MNEMO_SUPABASE_CONFIG;
const db = window.supabase?.createClient(config?.url, config?.publishableKey);
const state = { screen: "auth", authMode: "signup", session: null, user: null, spaces: [], spaceId: null, studyIndex: 0, phase: 0, search: "", loading: true };
const app = document.querySelector("#app");
const modalRoot = document.querySelector("#modal-root");
const toastRoot = document.querySelector("#toast-root");

const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&gt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[char]));
const initials = (name) => name.split(" ").map((word) => word[0]).join("").slice(0, 2).toUpperCase();
const button = (label, action, variant = "") => `<button type="button" class="btn ${variant}" data-action="${action}">${label}</button>`;
function toast(message) { toastRoot.innerHTML = `<div class="toast">${esc(message)}</div>`; window.setTimeout(() => toastRoot.innerHTML = "", 2800); }
function currentSpace() { return state.spaces.find((item) => item.id === state.spaceId) || state.spaces[0]; }
function currentCard() { const space = currentSpace(); return space?.cards[state.studyIndex % space.cards.length]; }

async function loadAppData() {
  if (!state.session) return;
  state.loading = true; render();
  const [profileResponse, spacesResponse] = await Promise.all([
    db.from("profiles").select("id, display_name").eq("id", state.session.user.id).single(),
    db.from("spaces").select("id, name, description, owner_id, invite_code, created_at, field_definitions(id,title,position), cards(id,values,created_by,last_edited_by,created_at,updated_at), space_members(user_id,role)").order("created_at", { ascending: true })
  ]);
  if (spacesResponse.error) { state.loading = false; state.dbError = spacesResponse.error.message; render(); return; }
  if (profileResponse.error) { state.loading = false; state.dbError = profileResponse.error.message; render(); return; }
  const spaces = (spacesResponse.data || []).map((space) => ({ ...space, fields: (space.field_definitions || []).sort((a,b) => a.position - b.position), cards: (space.cards || []).sort((a,b) => new Date(b.updated_at) - new Date(a.updated_at)) }));
  const memberIds = [...new Set(spaces.flatMap((space) => space.space_members.map((member) => member.user_id)))];
  let profiles = [];
  if (memberIds.length) { const { data } = await db.from("profiles").select("id,display_name").in("id", memberIds); profiles = data || []; }
  const names = new Map(profiles.map((profile) => [profile.id, profile.display_name]));
  state.user = { id: state.session.user.id, name: profileResponse.data.display_name, initials: initials(profileResponse.data.display_name) };
  state.spaces = spaces.map((space) => ({ ...space, members: space.space_members.map((member) => ({ ...member, name: names.get(member.user_id) || "Mnemo learner", initials: initials(names.get(member.user_id) || "Mnemo learner") })) }));
  state.spaceId = state.spaces.some((space) => space.id === state.spaceId) ? state.spaceId : state.spaces[0]?.id || null;
  state.loading = false; state.dbError = null; render();
}

function render() { if (!config || !db) return renderConfigError(); if (state.loading) return app.innerHTML = `<div class="empty" style="margin:10vh auto;max-width:440px"><h2>Opening Mnemo…</h2><p>Connecting your learning spaces.</p></div>`; if (!state.session) return renderAuth(); if (state.dbError) return renderDbError(); renderApp(); }
function renderConfigError() { app.innerHTML = `<div class="empty" style="margin:10vh auto;max-width:500px"><h2>Supabase configuration is missing</h2><p>Add the project URL and publishable key to <code>supabase-config.js</code>.</p></div>`; }
function renderDbError() { app.innerHTML = `<section class="auth"><div class="auth-art"><div class="brand"><span class="brand-mark"></span>mnemo</div><div class="auth-copy"><div class="eyebrow">Database setup</div><h1>One small step remains.</h1><p>Mnemo is connected to Supabase, but its tables and access rules have not been created yet.</p></div></div><div class="auth-panel"><div class="auth-form"><h2>Run the setup script</h2><p>In Supabase, open SQL Editor, paste <code>supabase-schema.sql</code>, and select Run. Then reload this page.</p><p class="form-hint">Supabase said: ${esc(state.dbError)}</p>${button("Try again", "reload-data", "primary block")}</div></div></section>`; }
function renderAuth() { const login = state.authMode === "login"; app.innerHTML = `<section class="auth"><div class="auth-art"><div class="brand"><span class="brand-mark"></span>mnemo</div><div class="auth-copy"><div class="eyebrow">Learn by connection</div><h1>Give every memory a place to land.</h1><p>Build vivid, shared mnemonic journeys with the people learning alongside you.</p></div><footer>Small connections become lasting memory.</footer></div><div class="auth-panel"><form class="auth-form" id="auth-form"><h2>${login ? "Welcome back." : "Make learning stick."}</h2><p>${login ? "Sign in to continue your learning journey." : "Create a space for the things you want to remember."}</p>${!login ? `<div class="form-row"><label for="name">Your name</label><input id="name" required maxlength="80" placeholder="Alex Smith" /></div>` : ""}<div class="form-row"><label for="email">Email</label><input id="email" type="email" required placeholder="you@example.com" /></div><div class="form-row"><label for="password">Password</label><input id="password" type="password" minlength="6" required placeholder="At least 6 characters" /></div><button class="btn primary block" type="submit">${login ? "Sign in" : "Create account"}</button><p class="auth-switch">${login ? "New to Mnemo?" : "Already have an account?"} <button type="button" class="text-button" data-action="toggle-auth">${login ? "Create an account" : "Sign in"}</button></p></form></div></section>`; }
function shell(content) { const space = currentSpace(); return `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark"></span>mnemo</div><button type="button" class="space-switcher" data-action="go-dashboard"><span class="caption">Current space</span><strong>${space ? esc(space.name) : "Choose a space"}⌄</strong></button><nav class="nav"><button type="button" class="${state.screen === "dashboard" ? "active" : ""}" data-action="go-dashboard"><span class="nav-icon">▦</span><span class="nav-label">Overview</span></button><button type="button" class="${state.screen === "cards" ? "active" : ""}" data-action="go-cards"><span class="nav-icon">▤</span><span class="nav-label">Cards</span></button><button type="button" class="${state.screen === "study" ? "active" : ""}" data-action="go-study"><span class="nav-icon">✦</span><span class="nav-label">Study</span></button><button type="button" class="${state.screen === "settings" ? "active" : ""}" data-action="go-settings"><span class="nav-icon">⚙</span><span class="nav-label">Settings</span></button></nav><div class="sidebar-user"><span class="avatar">${state.user.initials}</span><div>${esc(state.user.name)}<small><button type="button" class="text-button" data-action="sign-out">Sign out</button></small></div></div></aside><main class="main">${content}</main></div>`; }
function renderApp() { const views = { dashboard: dashboardView, cards: cardsView, study: studyView, settings: settingsView }; app.innerHTML = shell((views[state.screen] || dashboardView)()); }
function dashboardView() { const space = currentSpace(); return `<div class="topbar"><div><div class="eyebrow">Your learning spaces</div><h1>Keep the thread going.</h1><p>Small connections become lasting memory.</p></div><div class="actions">${button("＋ Join space", "join-space")}${button("＋ Create space", "create-space", "primary")}</div></div>${space ? `<section class="hero"><div><div class="eyebrow">Your next session</div><h2>${esc(space.name)}</h2><p>Continue with ${space.cards.length} cards waiting for a first look.</p>${button("Start studying ↗", "go-study", "orange")}</div><div class="progress-box"><div class="progress-label"><span>Weekly rhythm</span><span>4 / 6 sessions</span></div><div class="progress"><span style="width:68%"></span></div></div></section>` : ""}<div class="section-head"><h2>Your spaces</h2><span class="card-detail">${state.spaces.length} active</span></div><section class="space-grid">${state.spaces.length ? state.spaces.map(spaceTile).join("") : `<div class="empty"><h2>Your first learning space starts here</h2><p>Create a space, define its card fields, and invite friends when you are ready.</p>${button("Create your first space", "create-space", "primary")}</div>`}</section>`; }
function spaceTile(space) { return `<article class="space-tile"><div class="tile-top"><span class="tag">${space.members.length} learners</span><button type="button" class="icon-dot" data-action="open-space" data-id="${space.id}" aria-label="Open ${esc(space.name)}">•••</button></div><div><h3>${esc(space.name)}</h3><p class="card-detail">${esc(space.description)}</p></div><div class="tile-meta"><span>${space.cards.length} cards</span><span>Open space →</span></div></article>`; }
function cardsView() { const space = currentSpace(); if (!space) return dashboardView(); const query = state.search.toLowerCase(); const cards = space.cards.filter((card) => Object.values(card.values || {}).some((value) => String(value).toLowerCase().includes(query))); return `<div class="space-head"><button type="button" class="breadcrumbs" data-action="go-dashboard">← All spaces</button><div class="topbar"><div><h1>${esc(space.name)}</h1><p>${esc(space.description)}</p></div><div class="actions">${button("Invite", "invite")}${button("＋ Add card", "add-card", "primary")}</div></div></div><div class="toolbar"><div class="search"><input id="card-search" value="${esc(state.search)}" placeholder="Search every field" /></div><span class="card-detail">${cards.length} of ${space.cards.length} cards</span></div><section class="card-grid">${cards.length ? cards.map((card) => cardTile(card, space)).join("") : `<div class="empty"><h2>No cards yet</h2><p>Add a shared memory chain for this space.</p>${button("Add card", "add-card", "primary")}</div>`}</section>`; }
function cardTile(card, space) { const first = space.fields[0]; const pronunciation = space.fields[1]; const meaning = space.fields[2]; return `<article class="mnemo-card"><div class="tile-top"><span class="tag">${esc(first.title)}</span><button type="button" class="icon-dot" data-action="edit-card" data-id="${card.id}" aria-label="Edit card">•••</button></div><div><h3 class="card-term">${esc(card.values?.[first.id] || "Untitled")}</h3><p class="card-detail">${esc(card.values?.[pronunciation?.id] || "")} ${meaning ? `· ${esc(card.values?.[meaning.id] || "")}` : ""}</p></div><div class="card-meta"><span>Shared card</span><span>${space.fields.length} fields</span></div></article>`; }
function studyView() { const space = currentSpace(); if (!space?.cards.length) return `<div class="study-head"><button type="button" class="breadcrumbs" data-action="go-cards">← Back to cards</button></div><div class="empty"><h2>Your study deck is waiting</h2><p>Add a card first, then return here to practise its memory chain.</p>${button("Add your first card", "add-card", "primary")}</div>`; const card = currentCard(); const field = space.fields[Math.min(state.phase, space.fields.length - 1)]; const phaseDots = space.fields.map((_, index) => `<span class="${index <= state.phase ? "active" : ""}"></span>`).join(""); return `<div class="study-head"><button type="button" class="breadcrumbs" data-action="go-cards">← Back to cards</button><div class="eyebrow">${esc(space.name)} · Card ${state.studyIndex + 1} / ${space.cards.length}</div></div><section class="study-stage"><div class="study-wrap"><article class="study-card ${state.phase ? "flipped" : ""}"><div class="study-face study-front"><div><div class="eyebrow">${esc(space.fields[0].title)} · field 1 of ${space.fields.length}</div><div class="phase-dots">${phaseDots}</div></div><div><div class="study-word">${esc(card.values?.[space.fields[0].id] || "")}</div>${space.fields[1] ? `<div class="pronunciation">${esc(card.values?.[space.fields[1].id] || "")}</div>` : ""}</div><div class="study-note">Recall the connection before revealing the next cue.</div></div><div class="study-face study-back"><div><div class="eyebrow">${esc(field.title)} · field ${state.phase + 1} of ${space.fields.length}</div><div class="phase-dots">${phaseDots}</div></div><div class="reveal-block"><div class="eyebrow">${esc(field.title)}</div><strong>${esc(card.values?.[field.id] || "—")}</strong></div><div class="study-note">${state.phase < space.fields.length - 1 ? "Take a breath—what comes next?" : "You’ve reached the full memory chain."}</div></div></article></div></section><div class="study-controls">${button("← Previous", "study-prev")}${state.phase < space.fields.length - 1 ? button("Reveal next", "study-reveal", "primary") : button("Got it ✓", "study-next", "primary")}${button("Next card →", "study-next")}</div>`; }
function settingsView() { const space = currentSpace(); if (!space) return dashboardView(); const owner = space.owner_id === state.user.id; return `<div class="space-head"><button type="button" class="breadcrumbs" data-action="go-cards">← ${esc(space.name)}</button><h1>Space settings</h1><p>Shape the way this group remembers together.</p></div><div class="settings-grid"><section class="panel"><h2>Card fields</h2><p>Fields reveal in this order during study mode. ${owner ? "Only you can change this structure." : "Only the space owner can change this structure."}</p><div id="field-list">${space.fields.map((field, index) => `<div class="field-row"><span class="field-index">${index + 1}</span><input data-field-id="${field.id}" value="${esc(field.title)}" aria-label="Field ${index + 1}" ${owner ? "" : "disabled"} /><button type="button" class="btn danger" data-action="delete-field" data-id="${field.id}" ${owner && space.fields.length > 2 ? "" : "disabled"}>Remove</button></div>`).join("")}</div>${owner ? `${button("＋ Add field", "add-field")}${button("Save field names", "save-fields", "primary")}` : ""}</section><aside class="panel"><h2>Members</h2><p>${space.members.length} people are learning here.</p>${space.members.map((member) => `<div class="member-row"><div class="member"><span class="avatar">${member.initials}</span><div>${esc(member.name)}<small>${esc(member.role)}</small></div></div></div>`).join("")}${button("Invite members", "invite", "primary block")}</aside></div>`; }

function openModal(content) { modalRoot.innerHTML = `<div class="modal-backdrop" data-action="close-modal"><section class="modal" role="dialog" aria-modal="true">${content}</section></div>`; }
function closeModal() { modalRoot.innerHTML = ""; }
function spaceModal() { openModal(`<h2>Create a space</h2><p>Start a new learning journey. You can invite friends as soon as it exists.</p><form id="space-form"><div class="form-row"><label for="space-name">Space name</label><input id="space-name" required maxlength="120" placeholder="e.g. Farsi Foundations" /></div><div class="form-row"><label for="space-description">Description <span class="card-detail">optional</span></label><textarea id="space-description" placeholder="What are you learning together?"></textarea></div><div class="form-row"><label for="space-fields">Fields <span class="card-detail">separate with commas</span></label><input id="space-fields" required value="Term, Pronunciation, Meaning, Mnemonic" /></div><div class="modal-actions">${button("Cancel", "close-modal")}${button("Create space", "submit-space", "primary")}</div></form>`); }
function cardModal(card = null) { const space = currentSpace(); openModal(`<h2>${card ? "Edit card" : "Add a card"}</h2><p>Build a memory chain your whole space can use.</p><form id="card-form" data-card-id="${card?.id || ""}">${space.fields.map((field, index) => `<div class="form-row"><label for="card-${field.id}">${esc(field.title)}${index ? " <span class=\"card-detail\">optional</span>" : ""}</label>${index === space.fields.length - 1 ? `<textarea id="card-${field.id}">${esc(card?.values?.[field.id] || "")}</textarea>` : `<input id="card-${field.id}" ${index === 0 ? "required" : ""} value="${esc(card?.values?.[field.id] || "")}" />`}</div>`).join("")}<div class="modal-actions">${card ? button("Delete", "delete-card", "danger") : ""}${button("Cancel", "close-modal")}${button("Save card", "submit-card", "primary")}</div></form>`); }
function inviteModal() { const space = currentSpace(); openModal(`<h2>Invite a learning partner</h2><p>Share this code with someone you trust. They’ll get full editing access to this space.</p><div class="code">${esc(space.invite_code)}</div><div class="modal-actions">${button("Close", "close-modal")}${button("Copy code", "copy-code", "primary")}</div>`); }
function joinModal() { openModal(`<h2>Join a space</h2><p>Ask a friend for their invite code, then you can learn and edit together.</p><form id="join-form"><div class="form-row"><label for="invite-code">Invite code</label><input id="invite-code" required placeholder="e.g. DUST-4827" /></div><div class="modal-actions">${button("Cancel", "close-modal")}${button("Join space", "submit-join", "primary")}</div></form>`); }

async function handleAuth(form) { const email = form.querySelector("#email").value.trim(); const password = form.querySelector("#password").value; let result; if (state.authMode === "login") result = await db.auth.signInWithPassword({ email, password }); else result = await db.auth.signUp({ email, password, options: { data: { display_name: form.querySelector("#name").value.trim() } } }); if (result.error) return toast(result.error.message); if (state.authMode === "signup" && !result.data.session) toast("Check your email to confirm your account, then sign in."); }
async function handleAction(action, trigger) {
  const space = currentSpace();
  if (action === "toggle-auth") { state.authMode = state.authMode === "login" ? "signup" : "login"; render(); return; }
  if (action === "sign-out") { await db.auth.signOut(); return; }
  if (action === "reload-data") return loadAppData();
  if (action === "go-dashboard") { state.screen = "dashboard"; render(); return; }
  if (action === "go-cards") { state.screen = "cards"; state.search = ""; render(); return; }
  if (action === "go-study") { state.screen = "study"; state.phase = 0; render(); return; }
  if (action === "go-settings") { state.screen = "settings"; render(); return; }
  if (action === "open-space") { state.spaceId = trigger.dataset.id; state.screen = "cards"; render(); return; }
  if (action === "create-space") return spaceModal(); if (action === "join-space") return joinModal(); if (action === "invite") return inviteModal(); if (action === "add-card") return cardModal(); if (action === "edit-card") return cardModal(space.cards.find((card) => card.id === trigger.dataset.id));
  if (action === "close-modal") { closeModal(); return; }
  if (action === "copy-code") { await navigator.clipboard?.writeText(space.invite_code); trigger.textContent = "Copied ✓"; toast("Invite code copied."); return; }
  if (action === "study-reveal") { state.phase = Math.min(state.phase + 1, space.fields.length - 1); render(); return; }
  if (action === "study-prev") { if (state.phase) state.phase--; else state.studyIndex = (state.studyIndex - 1 + space.cards.length) % space.cards.length; render(); return; }
  if (action === "study-next") { state.studyIndex = (state.studyIndex + 1) % space.cards.length; state.phase = 0; render(); return; }
  if (action === "add-field") { space.fields.push({ id: crypto.randomUUID(), title: "New field", position: space.fields.length }); render(); return; }
  if (action === "delete-field") { space.fields = space.fields.filter((field) => field.id !== trigger.dataset.id); render(); return; }
  if (action === "save-fields") { const fields = [...document.querySelectorAll("[data-field-id]")].map((input, position) => ({ id: input.dataset.fieldId, title: input.value.trim() || "Untitled field", position })); const { error } = await db.rpc("save_fields", { p_space_id: space.id, p_fields: fields }); if (error) return toast(error.message); toast("Field names saved."); return loadAppData(); }
  if (action === "submit-space") { const form = document.querySelector("#space-form"); if (!form.reportValidity()) return; const fields = form.querySelector("#space-fields").value.split(",").map((value) => value.trim()).filter(Boolean).slice(0, 8); if (fields.length < 2) return toast("A space needs at least two fields."); const { data, error } = await db.rpc("create_space", { p_name: form.querySelector("#space-name").value.trim(), p_description: form.querySelector("#space-description").value.trim(), p_fields: fields }); if (error) return toast(error.message); state.spaceId = data; state.screen = "cards"; closeModal(); toast("Space created."); return loadAppData(); }
  if (action === "submit-card") { const form = document.querySelector("#card-form"); if (!form.reportValidity()) return; const values = Object.fromEntries(space.fields.map((field) => [field.id, form.querySelector(`#card-${field.id}`).value.trim()])); const cardId = form.dataset.cardId || null; const payload = cardId ? { id: cardId, values, last_edited_by: state.user.id } : { space_id: space.id, values, created_by: state.user.id, last_edited_by: state.user.id }; const query = cardId ? db.from("cards").update(payload).eq("id", cardId) : db.from("cards").insert(payload); const { error } = await query; if (error) return toast(error.message); closeModal(); toast(cardId ? "Card updated." : "Card added to the space."); return loadAppData(); }
  if (action === "delete-card") { const id = document.querySelector("#card-form").dataset.cardId; const { error } = await db.from("cards").delete().eq("id", id); if (error) return toast(error.message); closeModal(); toast("Card deleted."); return loadAppData(); }
  if (action === "submit-join") { const code = document.querySelector("#invite-code").value.trim(); const { data, error } = await db.rpc("join_space_by_code", { p_code: code }); if (error) return toast(error.message); state.spaceId = data; state.screen = "cards"; closeModal(); toast("You joined the space."); return loadAppData(); }
}

document.addEventListener("submit", async (event) => { event.preventDefault(); if (event.target.id === "auth-form") await handleAuth(event.target); });
app.addEventListener("input", (event) => { if (event.target.id === "card-search") { state.search = event.target.value; renderApp(); document.querySelector("#card-search")?.focus(); } });
document.addEventListener("click", async (event) => { const trigger = event.target.closest("[data-action]"); if (!trigger) return; if (trigger.dataset.action === "close-modal" && event.target !== trigger) return; await handleAction(trigger.dataset.action, trigger); });

async function init() { if (!db) return render(); const { data: { session } } = await db.auth.getSession(); state.session = session; state.loading = Boolean(session); render(); if (session) await loadAppData(); db.auth.onAuthStateChange((_event, session) => { state.session = session; state.loading = Boolean(session); state.spaces = []; state.spaceId = null; render(); if (session) window.setTimeout(loadAppData, 0); }); }
init();
